### PR TITLE
Allow summoning Water/Air Elementals/Avatars on Water

### PR DESCRIPTION
**Pull request by Slayer95**
This came up when talking to IPS.

### CODE REVIEW

**Comment by Slayer95** [comment]
I wonder whether summoning Air Elementals on Q=Un-walkable should also be enabled.

**Comment by inferno8** [comment]
> I wonder whether summoning Air Elementals on Q=Un-walkable should also be enabled.

Most summoning circles require some sort of surface to be able to spawn an abysmal creature. This however does not apply to exotic things like Dimensional Gates. But this concept still hasn't been fleshed out, so there is room for clarification here.
I haven't checked, but if it is possible to summon a jinni on an unwalkable (chasm-like) tiles, then summoning Air Elementals there should also be possible.

**Comment by Slayer95** [comment]
> Most summoning circles require some sort of surface to be able to spawn an abysmal creature.

That's a good point. IMO, summoning on unwalkable would also have a huge gameplay impact.

> I haven't checked, but if it is possible to summon a jinni on an unwalkable (chasm-like) tiles, 

Nah, that's not currently possible.

Seeing Aerius "summon" an Air Elemental on Un-walkable was misleading though.

imagen

**Comment by inferno8** [comment]
> Seeing Aerius "summon" an Air Elemental on Un-walkable was misleading though.

Well, he is skilled professional - not only can he summon, but he is also a true magic user. This may explain that trick of summoning on an unwalkable tile. Summoners ironically know nothing about magic. They just use re-use powers coming directly from the Abyss and this has some limitations (they rely on circles, scrolls, environment etc.)

**Comment by Slayer95** [comment]
> I wonder whether summoning Air Elementals on Q=Un-walkable should also be enabled.

So, should this be a privilege of Sky Kingdom magi?

**Comment by inferno8** [comment]
> So, should this be a privilege of Sky Kingdom magi?

For this scenario, yes. In general I don't know. Being able to summon on unwalkable tiles could affect Sky Kingdom faction balance in MP and/or make Aeromancer's branch more powerful than the rest. I would leave this as it is.

**Comment by Slayer95** [comment]
All good

**Pull request merged**
