### PR TITLE
Attempt to fill `Banisher` unit description.

### PR DESCRIPTION
**Pull request by galegosimpatico**
This is the first time I ever do any UMC _development_. Beware noob mistakes :grimacing:.

Cheers and Regards,

### CODE REVIEW

**Comment by inferno8** [comment]
Looks promising. We will tweak it a little further if you don't mind 😉 Good job!

**Comment by galegosimpatico** [comment]
:bowing_man:

**Comment by inferno8** [comment]
Ok, these are our improvements:
_"Banishers represent the greatest level of skill a dispeller can achieve. They can send to the Abyss magical beings that are too powerful for their less experienced colleagues much more powerful than those a fellow Dispeller can. Like most experienced Summoners, Banishers march into battle with magical circles, but ones using the dispelling magic. It is unclear how or why circles of banishment work, but field scouts report multiple sightings of magical entities tending to destabilize when close to them, thus contributing to the Banishers' task."_

If you want to improve it, feel free to do so. If you approve it, please update your PR with this modified description, so we can merge it. 😉

**Comment by galegosimpatico** [comment]
Great, thanks. A couple doubts:

This one is not that important. I think you missed a comma?

> ```
> [...]
> [...] magical beings that are too powerful for their less experienced
> colleagues much more powerful than those a fellow Dispeller can. [...]
> [...]
> ```

Detail: 

```
[...] less experienced colleagues much more powerful than those a fellow [...]
                                 ^
                                 |
                                here
```

**SPOILERS AHEAD**

About the part:

> [...] Like most experienced Summoners, Banishers march into battle with magical circles, [...]

Originally I considered _into battle_ in my first draft, but quickly leaned towards _conflict_ influenced by the efreeti rebellion scenario of TBfW-TLU. Do you want to decouple the Era of Magic and TBfW-TLU that much? The election of the `Banisher` for a first contribution is not coincidental. I'm assuming that most times that text will be reached, it will be in the scope of TBfW-TLU.

**&lt;/SPOILERS&gt;**

All other changes I welcome and thank.

On absence of further comment I'll force push your text, just adding the comma perceived as missing.

Cheers,

**Comment by inferno8** [comment]
Yeah, the comma is missing.
Regarding the rest, the phrase "into battle" is more universal in my opinion. It fits a wider range of situations. Throughout the story Banishers proved to be efficient against other types of enemies, not only magicals. But personally I don't think this makes much difference. If you feel the phrase "to conflict" is more appropriate here, then use it. 😉

**Pull request merged**
